INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (161,"Expressa desejo de intensificar a capacidade de estabelecer metas alcançáveis");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (161,"Expressa desejo de intensificar a coerência entre expectativas e desejos");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (161,"Expressa desejo de intensificar a crença nas possibilidades");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (161,"Expressa desejo de intensificar a esperança");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (161,"Expressa desejo de intensificar a espiritualidade");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (161,"Expressa desejo de intensificar a interconexão com os outros");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (161,"Expressa desejo de reforçar a resolução de problemas para alcançar as metas");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (161,"Expressa desejo de reforçar o sentimento de sentido à vida");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Demonstra energia criativa (p. ex., escrever, fazer poesias, cantar)");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Lê literatura espiritual");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Ouve música");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Passa tempo ao ar livre");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Pede para integrar-se com pessoas significativas");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Presta serviços a outros");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Pede perdão a outros");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Pede para integrar-se com líderes espirituais");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Relata experiências místicas");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Reza");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Expressa veneração");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Expressa reverência");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Participa de atividades religiosas");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Expressa desejo de aumentar o amor");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Expressa desejo de aumentar o autoperdão");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Expressa desejo de aumentar o enfrentamento");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Expressa desejo de aumentar o significado da vida");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Expressa desejo de aumentar uma filosofia de vida satisfatória");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Expressa desejo de serenidade (p. ex., paz)");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Meditação");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Expressa desejo de aumentar a aceitação");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Expressa desejo de aumentar a alegria");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Expressa desejo de aumentar a coragem");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Expressa desejo de aumentar a entrega");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Expressa desejo de aumentar a esperança");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (163,"Expressa desejo de aumentar a finalidade da vida");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (164,"Foco em si mesmo");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (164,"Questiona as próprias crenças ao tentar chegar a uma decisão");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (164,"Questiona princípios morais ao tentar chegar a uma decisão");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (164,"Questiona regras morais ao tentar chegar a uma decisão");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (164,"Questiona valores morais ao tentar chegar a uma decisão");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (164,"Questiona valores pessoais ao tentar chegar a uma decisão");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (164,"Relata consequências indesejadas de ações alternativas que estão sendo consideradas");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (164,"Relata incerteza quanto a escolhas");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (164,"Relata sentimento de angústia ao tentar chegar a uma decisão");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (164,"Sinais físicos de angústia (p. ex., frequência cardíaca aumentada, inquietação)");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (164,"Sinais físicos de tensão");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (164,"Tomada de decisão adiada");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (164,"Vacilação entre escolhas alternativas");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (165,"Comportamento indicativo de falta de aderência");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (165,"Evidências de desenvolvimento de complicações");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (165,"Evidências de exacerbação de sintomas");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (165,"Falha em manter compromissos agendados");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (165,"Falha em progredir");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (165,"Testes objetivos que fornecem evidências de falha na aderência (p. ex., medidas fisiológicas, detecção de marcadores fisiológicos)");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (166,"Expressa desejo de reforçar costumes religiosos que proporcionaram religiosidade no passado");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (166,"Expressa desejo de reforçar padrões de crenças religiosas que proporcionaram religiosidade no passado");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (166,"Expressa desejo de reforçar padrões de crenças religiosas que proporcionaram conforto no passado");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (166,"Questiona padrões de costumes que são nocivos");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (166,"Questiona padrões de crença que são nocivos");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (166,"Rejeita padrões de crença que são nocivos");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (166,"Rejeita padrões de costumes que são nocivos");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (166,"Solicita ajuda para aumentar opções religiosas");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (166,"Solicita ajuda para aumentar a participação nas crenças religiosas prescritas (p. ex., adoração/ serviços religiosos, cerimônias religiosas, comportamentos religiosos privados/leitura de material, religioso/mídia, oração, regras/rituais alimentares, respeito a feriados, uso de vestimentas específicas)");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (166,"Solicita encontrar -se com líderes/ facilitadores religiosos");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (166,"Solicita experiências religiosas");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (166,"Solicita materiais religiosos");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (166,"Solicita o perdão");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (166,"Solicita reconciliação");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (167,"Dificuldade em aderir a crenças religiosas prescritas");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (167,"Dificuldade em aderir a rituais religiosos prescritos (p. ex., cerimônias religiosas, regras alimentares restritivas, roupas, oração, adoração/serviços religiosos, comportamentos religiosos privados/leitura de material religioso/mídía, respeito a feriados, encontros com líderes espirituais)");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (167,"Questiona costumes religiosos");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (167,"Questiona padrões de crenças religiosas");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (167,"Relata angústia espiritual por separação de uma comunidade religiosa");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (167,"Relata necessidade de reconectar-se com costumes anteriores");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (167,"Relata necessidade de reconectar-se com crenças anteriores");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"É incapaz de expressar estado de criatividade (p. ex., cantar/ ouvir música/ escrever)");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Não se interessa pela natureza");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Não se interessa por literatura espiritual");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Expressa alienação");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Recusa integrar-se com líderes espirituais");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Recusa integrar-se com pessoas significativas");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Relata estar separado de seu sistema de apoio");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Expressa desesperança");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Expressa raiva de um ser maior");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Expressa sentimento de abandono");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Expressa sofrimento");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Incapacidade de experimentar o transcendente");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Incapacidade de introspecção");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Incapacidade de participar de atividades religiosas");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Incapacidade de rezar");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Mudanças repentinas nas práticas espirituais");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Solicita conversar com um líder religioso");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Culpa");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Enfrentamento insatisfatório");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Expressa falta de aceitação");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Expressa falta de amor");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Expressa falta de autoperdão");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Expressa falta de coragem");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Expressa falta de esperança");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Expressa falta de finalidade na vida");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Expressa falta de serenidade (p. ex., paz)");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Expressa falta de significado na vida");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (169,"Raiva");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (171,"Expressa angústia (p. ex., impotência, culpa, frustração, ansiedade, dúvida sobre si mesmo, medo) em relação à dificuldade de agir de acordo com a própria escolha moral");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (172,"Expressa desejo de aumentar a análise de riscos/benefícios das decisões");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (172,"Expressa desejo de aumentar a coerência das decisões com metas pessoais");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (172,"Expressa desejo de aumentar a coerência das decisões com metas socioculturais");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (172,"Expressa desejo de aumentar a coerência das decisões com valores pessoais");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (172,"Expressa desejo de aumentar a coerência das decisões com valores socioculturais");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (172,"Expressa desejo de aumentar a compreensão das escolhas na tomada de decisão");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (172,"Expressa desejo de aumentar a compreensão do significado das escolhas");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (172,"Expressa desejo de fortalecer a tomada de decisão");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (172,"Expressa desejo de fortalecer o uso de evidências confiáveis para as decisões");
