INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (209,"Expressa desejo de aumentar a sensação de contentamento");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (209,"Expressa desejo de aumentar o relaxamento");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (209,"Expressa desejo de aumentar o conforto");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (209,"Expressa desejo de intensificar a resolução das queixas");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (210,"Ansiedade");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (210,"Choro");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (210,"Incapacidade de relaxar");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (210,"Inquietação");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (210,"Irritabilidade");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (210,"Lamentação");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (210,"Medo");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (210,"Padrão de sono perturbado");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (210,"Relato de falta de satisfação com a situação");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (210,"Relato de falta de sentir-se à vontade com a situação");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (210,"Relato de fome");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (210,"Relato de prurido");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (210,"Relato de sentir calor");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (210,"Relato de sentir frio");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (210,"Relato de sentir-se desconfortável");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (210,"Relato de sintomas de angústia");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (210,"Suspiros");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (211,"Alterações na pressão sanguínea");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (211,"Comportamento de distração (p.ex., andar de um lado para outro, procurar outras pessoas e/ou atividades, atividades repetidas)");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (211,"Comportamento de proteção");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (211,"Comportamento expressivo (p. ex., agitação, gemido, choro, vigilância, irritabilidade, suspiro)");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (211,"Diaforese");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (211,"Dilatação pupilar");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (211,"Distúrbio no padrão de sono");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (211,"Evidência observada de dor");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (211,"Expressão facial (p. ex., olhos sem brilho, aparência abatida, movimento fixo ou disperso, careta)");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (211,"Foco em si próprio");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (211,"Foco estreitado (p. ex., percepção do tempo alterada, processos de pensamento prejudicados, interação reduzida com pessoas e o ambiente)");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (211,"Gestos protetores");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (211,"Mudanças na frequência cardíaca");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (211,"Mudanças na freqüência respiratória");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (211,"Mudanças no apetite");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (211,"Posição para evitar dor");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (211,"Relato codificado (p. ex., uso da escala da dor)");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (211,"Relato verbal de dor");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (212,"Alteração da capacidade de continuar atividades prévias");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (212,"Anorexia");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (212,"Atrofia do grupo muscular envolvido");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (212,"Comportamento de proteção");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (212,"Comportamento observado de defesa");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (212,"Depressão");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (212,"Expressão facial (p. ex., olhos sem brilho, aparência abatida, movimento fixo ou disperso, careta)");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (212,"Fadiga");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (212,"Foco em si próprio");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (212,"Interação reduzida com as pessoas");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (212,"Inquietação");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (212,"Irritabilidade");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (212,"Medo de nova lesão");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (212,"Mudanças no padrão de sono");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (212,"Relato codificado (p. ex., escala de dor)");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (212,"Relato verbal de dor");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (212,"Respostas mediadas pelo sistema nervoso simpático (p. ex., temperatura, frio, mudanças na posição do corpo, hipersensibilidade)"
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (213,"Aversão à comida");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (213,"Deglutição aumentada");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (213,"Relato de gosto amargo na boca");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (213,"Relato de náusea");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (213,"Salivação aumentada");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (213,"Sensação de vontade de vomitar");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Ações repetitivas");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Ações sem sentido");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Afeto embotado");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Afeto triste");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Apresenta comportamento não aceito pelo grupo cultural dominante");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Ausência de pessoas significativas");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Comportamentos inapropriados para o estágio de desenvolvimento");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Doença");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Evidência de deficiência (p. ex., física, mental)");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Não comunicativo");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Preocupação com os próprios pensamentos");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Procura ficar sozinho");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Projeta hostilidade");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Retraído");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Sem contato visual");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Vive em uma subcultura");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Experimenta sentimentos de diferenças com relação aos outros");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Incapacidade de atender às expectativas de outros");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Insegurança em público");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Interesses inapropriados para idade/estágio de desenvolvimento");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Relato de inadequação de finalidade na vida");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Relato de sentimentos de rejeição");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Relato de sentimentos de solidão imposta por outros");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (214,"Relato de valores inaceitáveis para o grupo cultural dominante");
