//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PacienteVirtual.Resources.Mensagem", typeof(Mensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ação Alternativa.
        /// </summary>
        public static string acao_alternativa {
            get {
                return ResourceManager.GetString("acao_alternativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ação Queixa.
        /// </summary>
        public static string acao_queixa {
            get {
                return ResourceManager.GetString("acao_queixa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        public static string adicionar {
            get {
                return ResourceManager.GetString("adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumo de álcool.
        /// </summary>
        public static string alcool_consumo {
            get {
                return ResourceManager.GetString("alcool_consumo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parou o consumo.
        /// </summary>
        public static string alcool_parou {
            get {
                return ResourceManager.GetString("alcool_parou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de bebida alcoólica.
        /// </summary>
        public static string alcool_tipo_bebida {
            get {
                return ResourceManager.GetString("alcool_tipo_bebida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uso de álcool.
        /// </summary>
        public static string alcool_uso {
            get {
                return ResourceManager.GetString("alcool_uso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alergia.
        /// </summary>
        public static string alergia {
            get {
                return ResourceManager.GetString("alergia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativa.
        /// </summary>
        public static string ativa {
            get {
                return ResourceManager.GetString("ativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bebida.
        /// </summary>
        public static string bebida {
            get {
                return ResourceManager.GetString("bebida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastros.
        /// </summary>
        public static string cadastros {
            get {
                return ResourceManager.GetString("cadastros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumo de café.
        /// </summary>
        public static string cafe_consumo {
            get {
                return ResourceManager.GetString("cafe_consumo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parou o consumo de café.
        /// </summary>
        public static string cafe_parou {
            get {
                return ResourceManager.GetString("cafe_parou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uso de café.
        /// </summary>
        public static string cafe_uso {
            get {
                return ResourceManager.GetString("cafe_uso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo {0} só aceita &quot;M&quot; ou &quot;F&quot;.
        /// </summary>
        public static string campo_MouF {
            get {
                return ResourceManager.GetString("campo_MouF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *O campo &quot;{0}&quot; é obrigatório..
        /// </summary>
        public static string campo_requerido {
            get {
                return ResourceManager.GetString("campo_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string codigo {
            get {
                return ResourceManager.GetString("codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do Paciente.
        /// </summary>
        public static string codigo_paciente {
            get {
                return ResourceManager.GetString("codigo_paciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cógido do Sistema.
        /// </summary>
        public static string codigo_sistema {
            get {
                return ResourceManager.GetString("codigo_sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comportamento.
        /// </summary>
        public static string comportamento {
            get {
                return ResourceManager.GetString("comportamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção - Comportamento.
        /// </summary>
        public static string comportamento_atencao {
            get {
                return ResourceManager.GetString("comportamento_atencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Resposta Comportamento.
        /// </summary>
        public static string comportamento_resposta_codigo {
            get {
                return ResourceManager.GetString("comportamento_resposta_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Senha.
        /// </summary>
        public static string confirme_senha {
            get {
                return ResourceManager.GetString("confirme_senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta.
        /// </summary>
        public static string consulta {
            get {
                return ResourceManager.GetString("consulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta Dados Fixos.
        /// </summary>
        public static string consulta_dados_fixos {
            get {
                return ResourceManager.GetString("consulta_dados_fixos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Consulta Dados Fixos.
        /// </summary>
        public static string consulta_dados_fixos_codigo {
            get {
                return ResourceManager.GetString("consulta_dados_fixos_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta Dados Variáveis.
        /// </summary>
        public static string consulta_dados_variaveis {
            get {
                return ResourceManager.GetString("consulta_dados_variaveis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Consulta Dados Variáveis.
        /// </summary>
        public static string consulta_dados_variaveis_codigo {
            get {
                return ResourceManager.GetString("consulta_dados_variaveis_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulta Variável.
        /// </summary>
        public static string consulta_variavel {
            get {
                return ResourceManager.GetString("consulta_variavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Consulta Variável.
        /// </summary>
        public static string consulta_variavel_codigo {
            get {
                return ResourceManager.GetString("consulta_variavel_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cpf.
        /// </summary>
        public static string cpf {
            get {
                return ResourceManager.GetString("cpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar.
        /// </summary>
        public static string criar {
            get {
                return ResourceManager.GetString("criar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar Conta.
        /// </summary>
        public static string criar_conta {
            get {
                return ResourceManager.GetString("criar_conta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultural.
        /// </summary>
        public static string cultural {
            get {
                return ResourceManager.GetString("cultural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção - Cultura.
        /// </summary>
        public static string cultural_atencao {
            get {
                return ResourceManager.GetString("cultural_atencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Resposta Cultural.
        /// </summary>
        public static string cultural_resposta_codigo {
            get {
                return ResourceManager.GetString("cultural_resposta_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curso.
        /// </summary>
        public static string curso {
            get {
                return ResourceManager.GetString("curso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Atualização.
        /// </summary>
        public static string data_atualizacao {
            get {
                return ResourceManager.GetString("data_atualizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Envio.
        /// </summary>
        public static string data_envio {
            get {
                return ResourceManager.GetString("data_envio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Nascimento.
        /// </summary>
        public static string data_nascimento {
            get {
                return ResourceManager.GetString("data_nascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da Resposta.
        /// </summary>
        public static string data_resposta {
            get {
                return ResourceManager.GetString("data_resposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletar.
        /// </summary>
        public static string deletar {
            get {
                return ResourceManager.GetString("deletar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você tem certeza que deseja deletar esse dado?.
        /// </summary>
        public static string deletar_pergunta {
            get {
                return ResourceManager.GetString("deletar_pergunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados Demograficos e Antropometricos.
        /// </summary>
        public static string demografico_antropometricos {
            get {
                return ResourceManager.GetString("demografico_antropometricos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string descricao {
            get {
                return ResourceManager.GetString("descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição da Ação.
        /// </summary>
        public static string descricao_acao {
            get {
                return ResourceManager.GetString("descricao_acao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição da Queixa.
        /// </summary>
        public static string descricao_queixa {
            get {
                return ResourceManager.GetString("descricao_queixa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição da Razão do Encontro.
        /// </summary>
        public static string descricao_razao {
            get {
                return ResourceManager.GetString("descricao_razao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes.
        /// </summary>
        public static string detalhes {
            get {
                return ResourceManager.GetString("detalhes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diário Pessoal.
        /// </summary>
        public static string diario_pessoal {
            get {
                return ResourceManager.GetString("diario_pessoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disciplina.
        /// </summary>
        public static string disciplina {
            get {
                return ResourceManager.GetString("disciplina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosagem.
        /// </summary>
        public static string dosagem {
            get {
                return ResourceManager.GetString("dosagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string editar {
            get {
                return ResourceManager.GetString("editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eh Gabarito.
        /// </summary>
        public static string eh_gabarito {
            get {
                return ResourceManager.GetString("eh_gabarito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço de E-mail .
        /// </summary>
        public static string endereco_email {
            get {
                return ResourceManager.GetString("endereco_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar Solicitação de Matrícula.
        /// </summary>
        public static string enviar_solicitacao_turma {
            get {
                return ResourceManager.GetString("enviar_solicitacao_turma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolaridade.
        /// </summary>
        public static string escolaridade {
            get {
                return ResourceManager.GetString("escolaridade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialidade.
        /// </summary>
        public static string especialidade {
            get {
                return ResourceManager.GetString("especialidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espera tratamento.
        /// </summary>
        public static string espera_tratamento {
            get {
                return ResourceManager.GetString("espera_tratamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção - Espera tratamento.
        /// </summary>
        public static string espera_tratamento_atencao {
            get {
                return ResourceManager.GetString("espera_tratamento_atencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Resposta Espera Tratamento.
        /// </summary>
        public static string espera_tratamento_resposta_codigo {
            get {
                return ResourceManager.GetString("espera_tratamento_resposta_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado de Preenchimento.
        /// </summary>
        public static string estado_preenchimento {
            get {
                return ResourceManager.GetString("estado_preenchimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estilo de vida.
        /// </summary>
        public static string estilo_vida {
            get {
                return ResourceManager.GetString("estilo_vida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string excluir {
            get {
                return ResourceManager.GetString("excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiência com Medicamentos.
        /// </summary>
        public static string experiencia_medicamentos {
            get {
                return ResourceManager.GetString("experiencia_medicamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fisioterápico.
        /// </summary>
        public static string fitoterapico {
            get {
                return ResourceManager.GetString("fitoterapico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fone.
        /// </summary>
        public static string fone {
            get {
                return ResourceManager.GetString("fone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto.
        /// </summary>
        public static string foto {
            get {
                return ResourceManager.GetString("foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Género.
        /// </summary>
        public static string genero {
            get {
                return ResourceManager.GetString("genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grau Entendimento.
        /// </summary>
        public static string grau_entendimento {
            get {
                return ResourceManager.GetString("grau_entendimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção - Grau Entendimento.
        /// </summary>
        public static string grau_entendimento_atencao {
            get {
                return ResourceManager.GetString("grau_entendimento_atencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Resposta Grau Entendimento.
        /// </summary>
        public static string grau_entendimento_reposta_codigo {
            get {
                return ResourceManager.GetString("grau_entendimento_reposta_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupos Atividades.
        /// </summary>
        public static string grupo_atividades {
            get {
                return ResourceManager.GetString("grupo_atividades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to História do Paciente.
        /// </summary>
        public static string historia {
            get {
                return ResourceManager.GetString("historia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to História Familiar.
        /// </summary>
        public static string historia_familiar {
            get {
                return ResourceManager.GetString("historia_familiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to História Médica Pregressa.
        /// </summary>
        public static string historia_medica_pregressa {
            get {
                return ResourceManager.GetString("historia_medica_pregressa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to História de  Medicamento Pregresso.
        /// </summary>
        public static string historia_medicamento_pregressa {
            get {
                return ResourceManager.GetString("historia_medicamento_pregressa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histórico.
        /// </summary>
        public static string historico {
            get {
                return ResourceManager.GetString("historico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horário.
        /// </summary>
        public static string horario {
            get {
                return ResourceManager.GetString("horario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plano Incorporado.
        /// </summary>
        public static string incorporado_plano {
            get {
                return ResourceManager.GetString("incorporado_plano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção - Plano Incorporado.
        /// </summary>
        public static string incorporado_plano_atencao {
            get {
                return ResourceManager.GetString("incorporado_plano_atencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Resposta Incorporado Plano.
        /// </summary>
        public static string incorporado_plano_resposta_codigo {
            get {
                return ResourceManager.GetString("incorporado_plano_resposta_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicação.
        /// </summary>
        public static string indicacao {
            get {
                return ResourceManager.GetString("indicacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações da Conta.
        /// </summary>
        public static string informacao_conta {
            get {
                return ResourceManager.GetString("informacao_conta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instituição.
        /// </summary>
        public static string instituicao {
            get {
                return ResourceManager.GetString("instituicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da Instituição.
        /// </summary>
        public static string instituicao_codigo {
            get {
                return ResourceManager.GetString("instituicao_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da Instituição.
        /// </summary>
        public static string instituicao_nome {
            get {
                return ResourceManager.GetString("instituicao_nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lembrar-me.
        /// </summary>
        public static string lembrar_me {
            get {
                return ResourceManager.GetString("lembrar_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar.
        /// </summary>
        public static string listar {
            get {
                return ResourceManager.GetString("listar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listar Todos.
        /// </summary>
        public static string listar_todos {
            get {
                return ResourceManager.GetString("listar_todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrícula.
        /// </summary>
        public static string matricula {
            get {
                return ResourceManager.GetString("matricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicamento.
        /// </summary>
        public static string medicamento {
            get {
                return ResourceManager.GetString("medicamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Medicamento.
        /// </summary>
        public static string medicamento_codigo {
            get {
                return ResourceManager.GetString("medicamento_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicamento não prescrito.
        /// </summary>
        public static string medicamento_nao_prescrito {
            get {
                return ResourceManager.GetString("medicamento_nao_prescrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicamentos prescrito.
        /// </summary>
        public static string medicamento_prescrito {
            get {
                return ResourceManager.GetString("medicamento_prescrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicamentos.
        /// </summary>
        public static string medicamentos {
            get {
                return ResourceManager.GetString("medicamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicamentos anteriores.
        /// </summary>
        public static string medicamentos_anteriores {
            get {
                return ResourceManager.GetString("medicamentos_anteriores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Médicos que Atendem.
        /// </summary>
        public static string medicos_atendem {
            get {
                return ResourceManager.GetString("medicos_atendem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moradia da Família.
        /// </summary>
        public static string moradia_familia {
            get {
                return ResourceManager.GetString("moradia_familia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nível de Dificuldade.
        /// </summary>
        public static string nivel_dificuldade {
            get {
                return ResourceManager.GetString("nivel_dificuldade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nível de Escolaridade.
        /// </summary>
        public static string nivel_escolaridade {
            get {
                return ResourceManager.GetString("nivel_escolaridade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string nome {
            get {
                return ResourceManager.GetString("nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Medicamento.
        /// </summary>
        public static string nome_medicamento {
            get {
                return ResourceManager.GetString("nome_medicamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Paciente.
        /// </summary>
        public static string nome_paciente {
            get {
                return ResourceManager.GetString("nome_paciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da Pessoa.
        /// </summary>
        public static string nome_pessoa {
            get {
                return ResourceManager.GetString("nome_pessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Sistema.
        /// </summary>
        public static string nome_sistema {
            get {
                return ResourceManager.GetString("nome_sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Usuário.
        /// </summary>
        public static string nome_usuario {
            get {
                return ResourceManager.GetString("nome_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocupação.
        /// </summary>
        public static string ocupacao {
            get {
                return ResourceManager.GetString("ocupacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onde adquire os medicamentos.
        /// </summary>
        public static string onde_adquire_medicamentos {
            get {
                return ResourceManager.GetString("onde_adquire_medicamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opções.
        /// </summary>
        public static string opcoes {
            get {
                return ResourceManager.GetString("opcoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordem Cronológica.
        /// </summary>
        public static string ordem_cronologica {
            get {
                return ResourceManager.GetString("ordem_cronologica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paciente.
        /// </summary>
        public static string paciente {
            get {
                return ResourceManager.GetString("paciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do Paciente.
        /// </summary>
        public static string paciente_codigo {
            get {
                return ResourceManager.GetString("paciente_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Paciente.
        /// </summary>
        public static string paciente_nome {
            get {
                return ResourceManager.GetString("paciente_nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paciente Pessoa Turma.
        /// </summary>
        public static string paciente_pessoa_turma {
            get {
                return ResourceManager.GetString("paciente_pessoa_turma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paciente Virtual.
        /// </summary>
        public static string paciente_virtual {
            get {
                return ResourceManager.GetString("paciente_virtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetro Clínico.
        /// </summary>
        public static string parametro_clinico {
            get {
                return ResourceManager.GetString("parametro_clinico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pergunta.
        /// </summary>
        public static string pergunta {
            get {
                return ResourceManager.GetString("pergunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Pergunta.
        /// </summary>
        public static string pergunta_codigo {
            get {
                return ResourceManager.GetString("pergunta_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período.
        /// </summary>
        public static string periodo {
            get {
                return ResourceManager.GetString("periodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa.
        /// </summary>
        public static string pessoa {
            get {
                return ResourceManager.GetString("pessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Pessoa.
        /// </summary>
        public static string pessoa_codigo {
            get {
                return ResourceManager.GetString("pessoa_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plano de Saúde.
        /// </summary>
        public static string plano_saude {
            get {
                return ResourceManager.GetString("plano_saude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posologia.
        /// </summary>
        public static string posologia {
            get {
                return ResourceManager.GetString("posologia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencher.
        /// </summary>
        public static string preencher {
            get {
                return ResourceManager.GetString("preencher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preocupações.
        /// </summary>
        public static string preocupacoes {
            get {
                return ResourceManager.GetString("preocupacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção - Preocupações.
        /// </summary>
        public static string preocupacoes_atencao {
            get {
                return ResourceManager.GetString("preocupacoes_atencao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Resposta Preocupações.
        /// </summary>
        public static string preocupacoes_resposta_codigo {
            get {
                return ResourceManager.GetString("preocupacoes_resposta_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescritor.
        /// </summary>
        public static string prescritor {
            get {
                return ResourceManager.GetString("prescritor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade.
        /// </summary>
        public static string quantidade {
            get {
                return ResourceManager.GetString("quantidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queixa.
        /// </summary>
        public static string queixa {
            get {
                return ResourceManager.GetString("queixa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razão do Encontro.
        /// </summary>
        public static string razao_encontro {
            get {
                return ResourceManager.GetString("razao_encontro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registre - se.
        /// </summary>
        public static string registre_se {
            get {
                return ResourceManager.GetString("registre_se", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relato Clínico.
        /// </summary>
        public static string relato_clinico {
            get {
                return ResourceManager.GetString("relato_clinico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Relato.
        /// </summary>
        public static string relato_codigo {
            get {
                return ResourceManager.GetString("relato_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relato em Texto.
        /// </summary>
        public static string relato_texto {
            get {
                return ResourceManager.GetString("relato_texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relato Textual.
        /// </summary>
        public static string relato_textual {
            get {
                return ResourceManager.GetString("relato_textual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relato em Vídeo.
        /// </summary>
        public static string relato_video {
            get {
                return ResourceManager.GetString("relato_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string remover {
            get {
                return ResourceManager.GetString("remover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respostas.
        /// </summary>
        public static string resposta {
            get {
                return ResourceManager.GetString("resposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Resposta.
        /// </summary>
        public static string resposta_codigo {
            get {
                return ResourceManager.GetString("resposta_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string salvar {
            get {
                return ResourceManager.GetString("salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to se você não tiver uma conta..
        /// </summary>
        public static string se_nao_tem_conta {
            get {
                return ResourceManager.GetString("se_nao_tem_conta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione.
        /// </summary>
        public static string selecione {
            get {
                return ResourceManager.GetString("selecione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string senha {
            get {
                return ResourceManager.GetString("senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigla.
        /// </summary>
        public static string sigla {
            get {
                return ResourceManager.GetString("sigla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistema.
        /// </summary>
        public static string sistema {
            get {
                return ResourceManager.GetString("sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre.
        /// </summary>
        public static string sobre {
            get {
                return ResourceManager.GetString("sobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitar Matricula em Turma.
        /// </summary>
        public static string solicitar_matricula_turma {
            get {
                return ResourceManager.GetString("solicitar_matricula_turma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status do Preenchimento.
        /// </summary>
        public static string status_preenchimento {
            get {
                return ResourceManager.GetString("status_preenchimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumo de tabaco.
        /// </summary>
        public static string tabaco_consumo {
            get {
                return ResourceManager.GetString("tabaco_consumo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parou o consumo de tabaco.
        /// </summary>
        public static string tabaco_parou {
            get {
                return ResourceManager.GetString("tabaco_parou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uso de tabaco.
        /// </summary>
        public static string tabaco_uso {
            get {
                return ResourceManager.GetString("tabaco_uso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teste Arquivo Padrão - Resources.
        /// </summary>
        public static string teste {
            get {
                return ResourceManager.GetString("teste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Bebida.
        /// </summary>
        public static string tipo_bebida {
            get {
                return ResourceManager.GetString("tipo_bebida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turma.
        /// </summary>
        public static string turma {
            get {
                return ResourceManager.GetString("turma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Turma.
        /// </summary>
        public static string turma_codigo {
            get {
                return ResourceManager.GetString("turma_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Tutor.
        /// </summary>
        public static string tutor_codigo {
            get {
                return ResourceManager.GetString("tutor_codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentários do Tutor.
        /// </summary>
        public static string tutor_comentarios {
            get {
                return ResourceManager.GetString("tutor_comentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string usuario {
            get {
                return ResourceManager.GetString("usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string voltar {
            get {
                return ResourceManager.GetString("voltar", resourceCulture);
            }
        }
    }
}
