INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (77, "Conhecimento deficiente");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (77, "Doença");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (77, "Falta de familiaridade com os recursos da vizinhança");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (77, "Falta de modelo de papel");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (77, "Finanças insuficientes");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (77, "Funções prejudicadas");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (77, "Lesão");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (77, "Organização familiar insuficiente");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (77, "Planejamento familiar insuficiente");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (77, "Sistemas de apoio inadequados");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (76, "Abuso de drogas");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (76, "Capacidade executiva de processamento");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (76, "Depressão");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (76, "Disfunção do lobo frontal");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (76, "Estilo de vida/escolhas");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (76, "Fingimento de doença");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (76, "Importante estressor de vida");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (76, "Incapacidade para aprender");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (76, "Manutenção do controle");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (76, "Medo de internação ou institucionalização");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (76, "Prejuízo cognitivo (p. ex., demência)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (76, "Prejuízo funcional");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (76, "Síndrome de Capgras");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (76, "Transtorno da personalidade esquizofrênica");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (76, "Transtorno da personalidade paranoide");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (76, "Transtorno obsessivo-compulsivo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (75, "Ansiedade grave");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (75, "Barreiras ambientais");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (75, "Desconforto");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (75, "Dor");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (75, "Fadiga");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (75, "Fraqueza");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (75, "Motivação diminuída");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (75, "Prejuízo cognitivo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (75, "Prejuízo musculoesquelético");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (75, "Prejuízo neuromuscular");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (75, "Prejuízo perceptivo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (74, "Ansiedade grave");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (74, "Barreiras ambientais");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (74, "Capacidade de transferência prejudicada");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (74, "Dor");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (74, "Estado de mobilidade prejudicada");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (74, "Fadiga");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (74, "Fraqueza");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (74, "Motivação diminuída");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (74, "Prejuízo cognitivo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (74, "Prejuízo musculoesquelético");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (74, "Prejuízo neuromuscular");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (74, "Prejuízo perceptivo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (73, "Ansiedade grave");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (73, "Barreiras ambientais");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (73, "Diminuição de motivação");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (73, "Dor");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (73, "Fraqueza");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (73, "Incapacidade de perceber a relação espacial");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (73, "Incapacidade de perceber uma parte do corpo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (73, "Prejuízo cognitivo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (73, "Prejuízo musculoesquelético");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (73, "Prejuízo neuromuscular");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (73, "Prejuízo perceptivo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (72, "Ansiedade grave");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (72, "Barreiras ambientais");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (72, "Desconforto");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (72, "Diminuição da motivação");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (72, "Dor");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (72, "Fadiga");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (72, "Fraqueza");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (72, "Prejuízo cognitivo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (72, "Prejuízo musculoesquelético");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (72, "Prejuízo neuromuscular");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (72, "Prejuízo perceptivo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (70, "Fadiga da musculatura respiratória");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (70, "Fatores metabólicos");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (69, "Desobstrução ineficaz das vias aéreas");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (69, "Dor sem controle");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (69, "Nutrição inadequada");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (69, "Padrão de sono perturbado");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (69, "Ansiedade");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (69, "Autoestima diminuída");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (69, "Confiança insuficiente nos prestadores de cuidado");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (69, "Déficit de conhecimento sobre o processo de desmame");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (69, "Desesperança");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (69, "Ineficácia percebida do paciente quanto à capacidade de desmame");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (69, "Medo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (69, "Motivação diminuída");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (69, "Sentimento de impotência");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (69, "Ambiente adverso (p. ex., ambiente agitado e barulhento, eventos negativos no quarto, baixa proporção enfermeiros/pacientes, equipe de enfermagem não familiar)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (69, "Demandas de energia episódicas e não controladas");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (69, "História de dependência do ventilador por mais de quatro dias");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (69, "História de múltiplas tentativas de desmame malsucedidas");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (69, "Ritmo impróprio na diminuição do suporte ventilatório");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (69, "Suporte social inadequado");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (68, "Conhecimento deficiente de fatores agravantes (p. ex., tabagismo, estilo de vida sedentário, trauma, obesidade, ingestão de sal, imobilidade)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (68, "Conhecimento deficiente de processo de doença (p. ex., diabetes, hiperlipidemia)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (68, "Diabetes melito");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (68, "Estilo de vida sedentário");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (68, "Hipertensão");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (68, "Idade > 60 anos");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (68, "Procedimentos endovasculares");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (68, "Tabagismo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (67, "Conhecimento deficiente do processo da doença (p. ex., diabetes, hiperlipidemia)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (67, "Conhecimento deficiente dos fatores agravantes (p. ex., tabagismo, estilo de vida sedentário, trauma, obesidade, ingestão de sal, imobilidade)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (67, "Diabetes melito");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (67, "Estilo de vida sedentário");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (67, "Hipertensão");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (67, "Tabagismo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Abuso de drogas");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Aneurisma cerebral");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Aterosclerose aórtica");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Cardiomiopatia dilatada");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Coagulação intravascular disseminada");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Coagulopatia (p. ex., anemia falciforme)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Dissecção arterial");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Doença do nó sinusal");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Efeitos secundários relativos ao tratamento (bypass cardiopulmonar, medicamentos)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Embolia");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Endocardite infecciosa");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Estenose da carótida");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Estenose mitral");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Fibrilação atrial");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Hipercolesterolemia");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Hipertensão");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Infarto do miocárdio recente");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Mixoma atrial");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Neoplasia cerebral");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Segmento ventricular esquerdo acinético");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Tempo de protrombina anormal");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Tempo de tromboplastina parcial anormal");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Terapia trombolítica");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Trauma encefálico");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Tumor cerebral");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (66, "Válvula de prótese mecânica");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (65, "Abuso de drogas");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (65, "Anticoncepcionais");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (65, "Cirurgia cardíaca");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (65, "Diabetes melito");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (65, "Espasmo da artéria coronária");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (65, "Falta de conhecimento sobre os fatores de risco modificáveis (p. ex., tabagismo, estilo de vida sedentário, obesidade)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (65, "História familiar de doença da artéria coronária");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (65, "Hiperlipidemia");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (65, "Hipertensão");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (65, "Hipovolemia");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (65, "Hipoxemia");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (65, "Hipoxia");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (65, "Proteína C reativa elevada");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (65, "Tamponamento cardíaco");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Abuso de drogas");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Acidose metabólica");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Bypass cardiopulmonar");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Cirurgia cardíaca");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Diabetes melito");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Doença renal (rim policístico)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Efeitos secundários relacionados ao tratamento (p. ex., medicamentos, cirurgias)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Embolia vascular");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Estenose da artéria renal");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Exposição a nefrotóxicos");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Gênero feminino");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Glomerulonefrite");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Hiperlipidemia");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Hipertensão");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Hipertensão maligna");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Hipovolemia");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Hipoxemia");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Hipoxia");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Idade avançada");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Infecção (p. ex., sepse, infecção localizada)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Malignidade");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Necrose cortical bilateral");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Nefrite intersticial");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Poli trauma");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Polinefrite");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Queimaduras");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Síndrome compartimental abdominal");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Síndrome da resposta inflamatória sistêrnica");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Tabagismo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (64, "Vasculite");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (63, "Acidente vascular cerebral");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (63, "Anemia");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (63, "Aneurisma aórtico abdominal");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (63, "Coagulação intravascular disseminada");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (63, "Coagulopatia (p. ex., anemia falciforme)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (63, "Desempenho insatisfatório do ventrículo esquerdo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (63, "Diabetes melito");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (63, "Disfunção hepática");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (63, "Doença gastrintestinal (p. ex., úlcera duodenal ou gástrica, colite isquêmica, pancreatite isquêmica)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (63, "Doença vascular (p. ex., doença vascular periférica, doença oclusiva aortoilíaca)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (63, "Efeitos secundários relativos ao tratamento (p. ex., bypass cardiopulmonar, medicamentos, anestesia, cirurgia gástrica)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (63, "Hemorragia gastrintestinal aguda");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (63, "Idade > 60 anos");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (63, "Infarto do miocárdio");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (63, "Instabilidade hemo dinâmica");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (63, "Insuficiência renal");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (63, "Sexo feminino");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (63, "Síndrome compartimental abdominal");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (63, "Tabagismo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (63, "Tempo de protrombina");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (63, "Tempo parcial anormal de tromboplastina");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (63, "Trauma");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (63, "Varizes gastroesofágicas");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (62, "Ansiedade");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (62, "Dano musculoesquelético");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (62, "Dano neurológico");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (62, "Deformidade da parede do tórax");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (62, "Deformidade óssea");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (62, "Disfunção neuromuscular");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (62, "Dor");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (62, "Fadiga");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (62, "Fadiga da musculatura respiratória");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (62, "Hiperventilação");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (62, "Imaturidade neurológica");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (62, "Lesão da medula espinal");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (62, "Obesidade");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (62, "Posição do corpo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (62, "Síndrome da hipoventilaçào");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (61, "Estado de não condicionamento físico");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (61, "História prévia de intolerância à atividade");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (61, "Inexperiência com a atividade");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (61, "Presença de problemas circulatórios");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (61, "Presença de problemas respiratórios");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (60, "Desequilíbrio entre a oferta e a demanda de oxigênio");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (60, "Estilo de vida sedentário");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (60, "Fraqueza generalizada");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (60, "Imobilidade");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (60, "Repouso no leito");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (59, "Contratilidade alterada");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (59, "Frequência cardíaca alterada");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (59, "Pós-carga alterada");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (59, "Pré-carga alterada");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (59, "Ritmo alterado");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (59, "Volume de ejeção alterado");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (58, "Ambiente excessivamente estimulante");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (58, "Atrofia cortical");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (58, "Comportamento pré-mórbido (p. ex., personalidade extrovertida, sociável, demência pré-mórbica)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (58, "Estado emocional (p. ex., frustração ansiedade, tédio, depressão, agitação)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (58, "Estado ou necessidade fisiológica (p. ex., fome, sede, dor, vontade de urinar, constipação)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (58, "Hora do dia");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (58, "Prejuízo cognitivo (p. ex., déficits de memória e recordação, desorientação, capacidade visual-construtiva ou visual- espacial insatisfatória, defeitos de linguagem)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (58, "Sedação");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (58, "Separação de lugares familiares");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (57, "Barulho");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (57, "Luzes");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (57, "Temperatura");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (57, "Umidade");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (57, "Anemia");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (57, "Condição física debilitada");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (57, "Desnutrição");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (57, "Esforço físico aumentado");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (57, "Estados de doença");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (57, "Gravidez");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (57, "Privação de sono");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (57, "Ansiedade");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (57, "Depressão");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (57, "Estilo de vida enfadonho");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (57, "Estresse");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (57, "Eventos negativos na vida");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (57, "Ocupação");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (56, "Doença");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (56, "Gravidez Lesão");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (56, "Experiência perioperatória");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (56, "Imobilidade");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (56, "Quimioterapia");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (56, "Trabalho de parto e parto");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (56, "Crise de desenvolvimento relacionada à idade");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (56, "Dificuldades de desenvolvimento relacionadas à idade");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (56, "Ansiedade");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (56, "Dor");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (56, "Medo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (56, "Pesar");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (55, "Dor intensa");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (55, "Imobilização mecânica");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (55, "Imobilização prescrita");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (55, "Nível de consciência alterado");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (55, "Paralisia");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (54, "Conhecimento deficiente");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (54, "Descondicionamento");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (54, "Dor");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (54, "Força muscular insuficiente");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (54, "Limitações ambientais (p. ex., tamanho da cama, tipo de cama, equipamento para tratamento, imobilizadores)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (54, "Medicamentos sedativos");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (54, "Obesidade");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (54, "Prejuízo cognitivo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (54, "Prejuízo musculoesquelético");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (54, "Prejuízo neuromuscular");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Ansiedade");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Atraso de desenvolvimento");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Conhecimento deficiente quanto ao valor da atividade física");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Contraturas");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Controle muscular diminuído");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Crenças culturais em relação à atividade apropriada para a idade");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Descondicionamento");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Desconforto");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Desnutrição");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Desuso");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Diminuição da massa muscular");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Dor");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Estado de humor depressivo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Estilo de vida sedentário");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Falta de suporte socioambiental (p. ex., físico ou social)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Força muscular diminuída");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Índice de massa corporal acima dos 75 apropriados para a idade");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Intolerância à atividade");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Medicamentos");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Metabolismo celular alterado");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Perda de integridade de estruturas ósseas");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Prejuízo cognitivo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Prejuízos musculoesqueléticos");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Prejuízos neuromusculares");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Prejuízos sensório-perceptivos");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Resistência diminuída");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Relutância em iniciar o movimento");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Restrições prescritas de movimento");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Resistência cardiovascular limitada");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (53, "Rigidez articular");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (52, "Conhecimento deficiente");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (52, "Descondicionamento");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (52, "Dor");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (52, "Força muscular insuficiente");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (52, "Humor depressivo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (52, "Limites ambientais (p. ex., escadas, aclives e declives, superfícies irregulares, obstáculos sem segurança, distâncias, falta de dispositivos auxiliares ou de pessoa auxiliar, tipo de cadeira de rodas)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (52, "Obesidade");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (52, "Prejuízo cognitivo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (52, "Prejuízo musculoesquelético (p. ex., contraturas)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (52, "Prejuízo neuromuscular");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (52, "Resistência limitada");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (52, "Visão prejudicada");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (51, "Capacidade de resistência limitada");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (51, "Descondicionamento");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (51, "Dor");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (51, "Equilíbrio prejudicado");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (51, "Falta de conhecimento");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (51, "Força muscular insuficiente");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (51, "Humor depressivo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (51, "Limitações ambientais (p. ex., escadas, aclives e declives, superfícies irregulares, obstáculos sem segurança, distâncias, falta de dispositivos ou pessoas auxiliares, imobilizadores)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (51, "Medo de cair");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (51, "Obesidade");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (51, "Prejuízo cognitivo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (51, "Prejuízo musculoesquelético (p. ex., contraturas)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (51, "Prejuízo neuromuscular");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (51, "Visão prejudicada");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (50, "Descondicionamento");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (50, "Dor");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (50, "Equilíbrio prejudicado");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (50, "Falta de conhecimentos");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (50, "Força muscular insuficiente");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (50, "Limitações ambientais (p. ex., altura da cama, espaço inadequado, tipo de cadeira de rodas, equipamento para tratamento, imobilizadores)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (50, "Obesidade");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (50, "Prejuízo cognitivo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (50, "Prejuízo musculoesquelético (p. ex., contraturas)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (50, "Prejuízo neuromuscular");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (50, "Visão prejudicada");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (48, "Ambiente para o sono desconfortável por tempo prolongado");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (48, "Apneia do sono");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (48, "Assincronia circadiana sustentada");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (48, "Atividade diurna inadequada");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (48, "Demência");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (48, "Desconforto prolongado (p. ex., físico, psicológico)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (48, "Enurese relacionada ao sono");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (48, "Ereções dolorosas relacionadas ao sono");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (48, "Estimulação ambiental por tempo prolongado");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (48, "Higiene do sono inadequada por tempo prolongado");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (48, "Hipersonolência idiopática do sistema nervoso central");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (48, "Movimentos periódicos dos membros (p. ex., síndrome das pernas inquietas, mioclonia noturna)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (48, "Mudanças de estágios de sono relacionadas ao envelhecimento");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (48, "Narcolepsia");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (48, "Paralisia do sono familiar");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (48, "Pesadelos");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (48, "Práticas paternas/maternas que não favorecem o sono");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (48, "Síndrome do pôr do sol");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (48, "Sonambulismo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (48, "Terror noturno");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (48, "Uso prolongado de dietas contendo antissoporíficos (p. ex., cafeína)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (47, "Falta de privacidade/controle do sono");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (47, "Iluminação");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (47, "Imobilização física");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (47, "Interrupções (p. ex., motivos terapêuticos, monitoramento, exames laboratoriais)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (47, "Mobiliário estranho para dormir");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (47, "Mudança na exposição à luz diurna/escuridão");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (47, "Odores nocivos");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (47, "Responsabilidades de cuidado");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (47, "Ruído");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (47, "Sono do parceiro");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (47, "Temperatura/umidade do ambiente");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (46, "Ansiedade");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (46, "Cochilos frequentes durante o dia");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (46, "Depressão");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (46, "Desconforto físico (p. ex., dor, falta de ar, tosse, refluxo gastroesofágico, náusea, incontinência/urgência)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (46, "Estresse (p. ex., pensamentos ruminantes pré-sono)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (46, "Fatores ambientais (p. ex., ruído ambiental, exposição à luz do dia/escuridão, temperatura ambiental/umidade, ambiente desconhecido)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (46, "Higiene do sono inadequada (atual)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (46, "Ingestão de álcool");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (46, "Ingestão de estimulantes");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (46, "Medicamentos");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (46, "Medo");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (46, "Mudanças hormonais periódicas relacionadas ao gênero");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (46, "Padrão de atividades (p. ex., hora certa, quantidade)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (46, "Pesar");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (46, "Prejuízo do padrão de sono normal (p. ex., viagens, turno de trabalho)");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (46, "Responsabilidades de pai/mãe");
INSERT INTO `pv1`.`tb_diagnostico_fator` (`IdDiagnostico`, `DescricaoFator`) VALUES (46, "Sono interrompido");
