INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (78,"Conservação de tarefas motoras e visuais no lado não negligenciado");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (78,"Deixa a comida no prato do lado negligenciado");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (78,"Deslocamento de sons para o lado não negligenciado");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (78,"'Desvio' marcante da cabeça para o lado não negligenciado, para estímulos e atividades naquele lado w. Desvio marcante do tronco para o lado não negligenciado, para estímulos e atividades naquele lado");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (78,"'Desvio' marcante dos olhos para o lado não negligenciado, para estímulos e atividades naquele lado ");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (78,"Dificuldade para lembrar detalhes de cenas familiares com representação interna, localizadas no lado negligenciado");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (78,"Distorção de desenhos na metade da página relativa ao lado negligenciado");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (78,"Falha em cuidar da estética do lado negligenciado");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (78,"Falha em movimentar a cabeça no hemiespaço negligenciado, apesar de perceber umestímulo nesse espaço");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (78,"Falha em movimentar o tronco no hemiespaço negligenciado, apesar de perceber um estímulo nesse espaço");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (78,"Falha em movimentar os membros no hemiespaço negligenciado, apesar de perceber um estímulo nesse espaço");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (78,"Falha em movimentar os olhos no hemiespaço negligenciado, apesar de perceber um estímulo nesse espaço");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (78,"Falha em perceber pessoas que se aproximam a partir do lado negligenciado");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (78,"Falha em vestir o lado negligenciado");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (78,"Falha para cancelar linhas na metade da página relativa ao lado negligenciado");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (78,"Falta de precauções de segurança em relação ao lado negligenciado");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (78,"Omissão ao desenhar na metade da página correspondente ao lado negligenciado");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (78,"Parece não perceber posicionamento do membro negligenciado");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (78,"Substituição de letras ao ler, para formar palavras alternativas similares em extensão às originais");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (78,"Transferência da sensação de dor para o lado não negligenciado");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (78,"Uso de apenas metade vertical da página ao escrever");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (79,"Desorientação consistente");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (79,"Estados crônicos de confusão");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (79,"Incapacidade de concentrar-se");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (79,"Incapacidade de seguir instruções simples");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (79,"Lentidão para responder a perguntas");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (79,"Incapacidade de raciocinar");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (79,"Perda da função social");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (79,"Perda de trabalho");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (80,"Agitação aumentada");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (80,"Alucinações");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (80,"Falta de motivação para iniciar um comportamento voltado a uma meta");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (80,"Falta de motivação para iniciar um comportamento voluntário");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (80,"Falta de motivação para manter o comportamento voltado a uma meta");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (80,"Falta de motivação para manter um comportamento voluntário");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (80,"Flutuação na atividade psicomotora");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (80,"Flutuação na cognição");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (80,"Flutuação no nível de consciência");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (80,"Inquietação aumentada");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (80,"Percepções errôneas");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (83,"Evidência clínica de prejuízo orgânico");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (83,"Interpretação alterada");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (83,"Memória antiga prejudicada");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (83,"Memória recente prejudicada");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (83,"Nenhuma mudança no nível de consciência");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (83,"Personalidade alterada");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (83,"Prejuízo cognitivo existente há tempo");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (83,"Prejuízo cognitivo progressivo");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (83,"Resposta alterada a estímulos");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (83,"Socialização prejudicada");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (84,"Comportamentos exagerados");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (84,"Comportamentos impróprios (p. ex., histérico, hostil, agitado, apático)");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (84,"Desempenho inadequado em um teste");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (84,"Seguimento inadequado de instruções");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (84,"Verbalização do problema");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (85,"Comportamentos congruentes com o conhecimento expresso");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (85,"Demonstra conhecimentos sobre o tópico");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (85,"Descreve experiências prévias pertinentes ao tópico");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (85,"Expressa interesse em aprender");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (86,"Agir sem pensar");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (86,"Apostador patológico");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (86,"Busca de sensações");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (86,"Compartilhar detalhes pessoais de forma inadequada");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (86,"Familiaridade excessiva com estranhos");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (86,"Fazer perguntas pessoais a outros apesar do desconforto deles");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (86,"Incapacidade de poupar dinheiro ou regular as finanças");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (86,"Irritabilidade");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (86,"Promiscuidade sexual");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (86,"Repentes de temperamento");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (86,"Violência");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (87,"Esquecimento de efetuar uma ação em horário planejado");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (87,"Experiências de esquecimento");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (87,"Incapacidade de aprender novas habilidades");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (87,"Incapacidade de aprender novas informações");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (87,"Incapacidade de determinar se uma ação foi efetuada");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (87,"Incapacidade de executar habilidade previamente aprendida");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (87,"Incapacidade de recordar eventos");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (87,"Incapacidade de recordar informações reais");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (87,"Incapacidade de reter novas habilidades");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (87,"Incapacidade de reter novas informações");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (88,"É capaz de escrever em um idioma");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (88,"É capaz de falar um idioma");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (88,"Expressa desejo de aumentar a comunicação");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (88,"Expressa pensamentos");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (88,"Expressa satisfação com a capacidade de compartilhar ideias com terceiros");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (88,"Expressa satisfação com a capacidade de compartilhar informações com terceiros");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (88,"Expressa sentimentos");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (88,"Forma sentenças");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (88,"Forma frases");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (88,"Forma palavras");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (88,"Interpreta pistas não verbais adequadamente");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (88,"Usa indicadores não verbais adequadamente");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Ausência de contato visual");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Déficit visual parcial");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Déficit visual total");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Desorientação em relação a pessoas");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Desorientação no espaço");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Desorientação no tempo");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Dificuldade de usar a expressão corporal");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Dificuldade de usar a expressão facial");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Dificuldade na atenção seletiva");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Dificuldade para compreender o padrão usual de comunicação");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Dificuldade para expressar verbalmente os pensamentos (p. ex., afasia, disfasia, apraxia, dislexia)");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Dificuldade para formar sentenças");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Dificuldade para formar palavras (p. ex., afonia, dislalia, disartria)");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Dificuldade para manter o padrão usual de comunicação");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Dispneia");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Fala com dificuldade");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Gagueira");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Incapacidade de falar o idioma do cuidado r");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Incapacidade de usar expressões corporais");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Incapacidade de usar expressões faciais");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Não consegue falar");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Não fala");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Pronúncia indistinta");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Recusa obstinada a falar");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Verbaliza com dificuldade");
INSERT INTO `pv1`.`tb_diagnostico_caracteristica` (`IdDiagnostico`, `DescricaoCaracteristica`) VALUES (89,"Verbalização imprópria");
